name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.3.4

dependencies:
  cached_network_image:
  carousel_slider_plus:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  flutter_native_splash:
  readmore:
  smooth_page_indicator:
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-.ttf
